### ISSUE TITLE
Update support files for target OBD2LC_WIFI_CC32XX

### ISSUE THREAD

**Issue by mkowalczyk-intrepid** [intrepidcs/OBD2LC_WIFI_CC32XX#1]
We've added firmware features to OBD2LC ISM code that have a corresponding target update for OBD2LC_WIFI_CC32XX. I've already forked master and made the changes there. They should probably be merged into master and v908_maintenance branches, since LC support is in v908 now.

**Comment by mkowalczyk-intrepid** [comment]
Pull request is here:
https://github.com/intrepidcs/OBD2LC_WIFI_CC32XX/pull/2

**Comment by mkowalczyk-intrepid** [comment]
@wskellenger-intrepid

**Comment by wskellenger-intrepid** [comment]
@mkowalczyk-intrepid merged to master, I will also merge to v908_maintenance

**Comment by wskellenger-intrepid** [comment]
v908_maintenance was reset to e399737e137bba28481a92a1efdeff7dbacd449f.  Thanks @mkowalczyk-intrepid !!
